version: "3.3"
services:
  deu-db:
    image: mysql:5.7.33
    container_name: deu-mysql
    environment:
      - MYSQL_DATABASE=deu
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    volumes:
      - project_mysql_db:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  project_mysql_db: {}